services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: cats_pic_development

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cats_pic_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
